#!/usr/bin/env bash
# =============================================================================
# Cypress Zero-Ops — Metabase KPI/Dashboard Seed
# =============================================================================
# Creates Cypress Core BI collection, KPI cards, and an executive dashboard.
#
# Usage: ./scripts/seed-metabase-dashboards.sh
# =============================================================================
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ -f "$ROOT_DIR/.env" ]]; then
  set -a; source "$ROOT_DIR/.env"; set +a
fi

MB_HOST="${METABASE_HOST:-http://localhost:7050}"
MB_ADMIN_EMAIL="${METABASE_ADMIN_EMAIL:-andres@getcypress.xyz}"
MB_ADMIN_PASSWORD="${METABASE_ADMIN_PASSWORD:-CypressDev2026!}"
COLLECTION_NAME="Cypress Core BI"
DASHBOARD_NAME="Cypress Core - Executive Overview"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*" >&2; }
ok()    { echo -e "${GREEN}  ✔${NC} $*" >&2; }
warn()  { echo -e "${YELLOW}  ⚠${NC} $*" >&2; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

for i in $(seq 1 40); do
  status=$(curl -s -o /dev/null -w "%{http_code}" "$MB_HOST/api/health" || true)
  [[ "$status" == "200" ]] && break
  [[ "$i" == "40" ]] && err "Metabase is not ready at $MB_HOST"
  sleep 2
done

LOGIN_RESULT=$(curl -s -X POST "$MB_HOST/api/session" \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"$MB_ADMIN_EMAIL\",\"password\":\"$MB_ADMIN_PASSWORD\"}")
SESSION_ID=$(echo "$LOGIN_RESULT" | jq -r '.id // empty')
[[ -z "$SESSION_ID" ]] && err "Metabase login failed: $(echo "$LOGIN_RESULT" | jq -r '.message // .errors // "unknown"')"
ok "Metabase session obtained"

mb_api() {
  local method="$1" path="$2"
  shift 2
  curl -s -X "$method" "${MB_HOST}${path}" \
    -H "X-Metabase-Session: $SESSION_ID" \
    -H "Content-Type: application/json" \
    "$@"
}

CORE_DB_ID=$(mb_api GET /api/database | jq -r '.data[]? | select(.name=="Cypress Core") | .id // empty')
[[ -z "$CORE_DB_ID" ]] && err "Cypress Core data source not found. Run scripts/seed-metabase.sh first."
ok "Using Cypress Core data source ID: $CORE_DB_ID"

# ---------------------------------------------------------------------------
# Collection
# ---------------------------------------------------------------------------
COLLECTION_ID=$(mb_api GET /api/collection | jq -r ".[]? | select(.name==\"$COLLECTION_NAME\") | .id" | head -1)
if [[ -z "$COLLECTION_ID" ]]; then
  payload=$(jq -n --arg name "$COLLECTION_NAME" '{name:$name, color:"#509EE3", description:"Cypress Core analytics models and executive dashboards"}')
  COLLECTION_ID=$(mb_api POST /api/collection -d "$payload" | jq -r '.id // empty')
  [[ -z "$COLLECTION_ID" ]] && err "Failed to create collection"
  ok "Created collection: $COLLECTION_NAME ($COLLECTION_ID)"
else
  ok "Collection exists: $COLLECTION_NAME ($COLLECTION_ID)"
fi

# ---------------------------------------------------------------------------
# Dashboard
# ---------------------------------------------------------------------------
DASHBOARD_ID=$(mb_api GET /api/dashboard | jq -r ".[]? | select(.name==\"$DASHBOARD_NAME\") | .id" | head -1)
if [[ -z "$DASHBOARD_ID" ]]; then
  payload=$(jq -n --arg name "$DASHBOARD_NAME" --argjson cid "$COLLECTION_ID" '{name:$name, description:"Auto-generated KPI dashboard for Cypress Core", collection_id:$cid}')
  DASHBOARD_ID=$(mb_api POST /api/dashboard -d "$payload" | jq -r '.id // empty')
  [[ -z "$DASHBOARD_ID" ]] && err "Failed to create dashboard"
  ok "Created dashboard: $DASHBOARD_NAME ($DASHBOARD_ID)"
else
  ok "Dashboard exists: $DASHBOARD_NAME ($DASHBOARD_ID)"
fi

create_card() {
  local name="$1"
  local display="$2"
  local query="$3"

  local payload card_id existing_card_id

  existing_card_id=$(mb_api GET /api/card | jq -r --arg name "$name" --argjson cid "$COLLECTION_ID" \
    '.[]? | select(.name==$name and .collection_id==$cid) | .id' | tail -1)
  if [[ -n "$existing_card_id" ]]; then
    echo "$existing_card_id"
    return
  fi

  payload=$(jq -n \
    --arg name "$name" \
    --arg desc "Auto-generated by scripts/seed-metabase-dashboards.sh" \
    --arg display "$display" \
    --arg query "$query" \
    --argjson db "$CORE_DB_ID" \
    --argjson cid "$COLLECTION_ID" \
    '{
      name:$name,
      description:$desc,
      display:$display,
      collection_id:$cid,
      dataset_query:{
        database:$db,
        type:"native",
        native:{query:$query, "template-tags":{}}
      },
      visualization_settings:{}
    }')

  card_id=$(mb_api POST /api/card -d "$payload" | jq -r '.id // empty')
  [[ -z "$card_id" ]] && err "Failed creating card: $name"
  echo "$card_id"
}

info "Creating KPI cards..."

CARD_TOTAL_VEHICLES=$(create_card "KPI - Total Vehicles" "scalar" "SELECT COUNT(*)::bigint AS total_vehicles FROM \"Vehicle\";")
CARD_TOTAL_ORGS=$(create_card "KPI - Total Organizations" "scalar" "SELECT COUNT(*)::bigint AS total_organizations FROM \"Organization\";")
CARD_TOTAL_CAMPAIGNS=$(create_card "KPI - Total Campaigns" "scalar" "SELECT COUNT(*)::bigint AS total_campaigns FROM \"Campaign\";")

CARD_VEHICLE_STATUS=$(create_card "Vehicles by Lifecycle Status" "bar" "SELECT status::text AS status, COUNT(*)::bigint AS vehicles FROM \"Vehicle\" GROUP BY status ORDER BY vehicles DESC;")
CARD_OFFER_FUNNEL=$(create_card "Offers by Status" "bar" "SELECT status::text AS status, COUNT(*)::bigint AS offers FROM \"Offer\" GROUP BY status ORDER BY offers DESC;")
CARD_LISTING_STATUS=$(create_card "Listings by Status" "bar" "SELECT status::text AS status, COUNT(*)::bigint AS listings FROM \"Listing\" GROUP BY status ORDER BY listings DESC;")

CARD_ORG_TIER=$(create_card "Organizations by Tier" "pie" "SELECT tier::text AS tier, COUNT(*)::bigint AS organizations FROM \"Organization\" GROUP BY tier ORDER BY organizations DESC;")
CARD_CAMPAIGN_STATUS=$(create_card "Campaigns by Status" "bar" "SELECT status::text AS status, COUNT(*)::bigint AS campaigns FROM \"Campaign\" GROUP BY status ORDER BY campaigns DESC;")
CARD_MONTHLY_SALES=$(create_card "Monthly Vehicle Sales" "line" "SELECT DATE_TRUNC('month', COALESCE(\"saleCompletedAt\", \"updatedAt\")) AS month, COUNT(*)::bigint AS sold_vehicles FROM \"Vehicle\" WHERE status = 'SOLD' GROUP BY 1 ORDER BY 1;")

ok "KPI cards created"

info "Building dashboard layout..."

cards_payload=$(jq -n \
  --argjson c1 "$CARD_TOTAL_VEHICLES" \
  --argjson c2 "$CARD_TOTAL_ORGS" \
  --argjson c3 "$CARD_TOTAL_CAMPAIGNS" \
  --argjson c4 "$CARD_VEHICLE_STATUS" \
  --argjson c5 "$CARD_OFFER_FUNNEL" \
  --argjson c6 "$CARD_LISTING_STATUS" \
  --argjson c7 "$CARD_CAMPAIGN_STATUS" \
  --argjson c8 "$CARD_ORG_TIER" \
  --argjson c9 "$CARD_MONTHLY_SALES" \
  '{cards:[
    {id:-1, card_id:$c1, row:0, col:0, size_x:8, size_y:4, parameter_mappings:[]},
    {id:-2, card_id:$c2, row:0, col:8, size_x:8, size_y:4, parameter_mappings:[]},
    {id:-3, card_id:$c3, row:0, col:16, size_x:8, size_y:4, parameter_mappings:[]},
    {id:-4, card_id:$c4, row:4, col:0, size_x:12, size_y:7, parameter_mappings:[]},
    {id:-5, card_id:$c5, row:4, col:12, size_x:12, size_y:7, parameter_mappings:[]},
    {id:-6, card_id:$c6, row:11, col:0, size_x:12, size_y:7, parameter_mappings:[]},
    {id:-7, card_id:$c7, row:11, col:12, size_x:12, size_y:7, parameter_mappings:[]},
    {id:-8, card_id:$c8, row:18, col:0, size_x:8, size_y:7, parameter_mappings:[]},
    {id:-9, card_id:$c9, row:18, col:8, size_x:16, size_y:7, parameter_mappings:[]}
  ]}')

layout_result=$(mb_api PUT "/api/dashboard/$DASHBOARD_ID/cards" -d "$cards_payload")
cards_count=$(echo "$layout_result" | jq -r '.cards | length // 0')
[[ "$cards_count" -eq 0 ]] && err "Dashboard layout update failed"

ok "Dashboard layout completed"

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Metabase Dashboards Seeded${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Collection:  $COLLECTION_NAME ($COLLECTION_ID)"
echo "  Dashboard:   $DASHBOARD_NAME ($DASHBOARD_ID)"
echo "  URL:         $MB_HOST/dashboard/$DASHBOARD_ID"
echo ""
